CREATE DATABASE STORECO
GO

USE STORECO
GO


CREATE TABLE EMPLOYEE(
	EMP_CODE CHAR(6) NOT NULL,
	EMP_NAME NVARCHAR(30) NOT NULL, 
	EMP_PHONE CHAR(10) NOT NULL,
	EMP_ADDRESS NVARCHAR(100) NOT NULL, 
	EMP_SALARY NVARCHAR(100) ,
	MA_CODE CHAR(6) ,

	CONSTRAINT PK_EMP_CODE PRIMARY KEY(EMP_CODE) ,
)
GO

CREATE TABLE MANAGER(
	MA_CODE CHAR(6) NOT NULL,
	MA_NAME NVARCHAR(30) NOT NULL, 
	MA_PHONE CHAR(10) NOT NULL,
	MA_ADDRESS NVARCHAR(100) NOT NULL, 
	MA_SALARY NVARCHAR(100) ,

	CONSTRAINT PK_MA_CODE PRIMARY KEY(MA_CODE) ,
	CONSTRAINT CK_MA_NAME UNIQUE(MA_NAME),
)
GO

CREATE TABLE CUSTOMER(
	CUS_CODE CHAR(6) NOT NULL,
	CUS_NAME NVARCHAR(30) NOT NULL,
	CUS_PHONE CHAR(10) NOT NULL,
	CUS_ADDRESS NVARCHAR(100)

	CONSTRAINT PK_CUS_CODE PRIMARY KEY(CUS_CODE)
)
GO

CREATE TABLE KING_OF_PHONE(
	KOP_CODE CHAR(6) NOT NULL,
	KOP_NAME NVARCHAR(10) NOT NULL,

	CONSTRAINT PK_KOP_CODE PRIMARY KEY(KOP_CODE),
)
GO

CREATE TABLE PHONE(
	P_CODE CHAR(6) NOT NULL,
	P_NAME NVARCHAR(30) NOT NULL,
	P_BRAND NVARCHAR(30) NOT NULL,
	P_COST CHAR(100) NOT NULL,
	P_COSTIN CHAR(100) NOT NULL,
	P_NUMBER CHAR(10) NOT NULL ,
	KOP_CODE CHAR(6) ,
	PUB_CODE CHAR(6) ,

	CONSTRAINT PK_P_CODE PRIMARY KEY(P_CODE),
	CONSTRAINT CK_P_NAME UNIQUE(P_NAME),
	CONSTRAINT FK_KOP_CODE FOREIGN KEY(KOP_CODE) REFERENCES KING_OF_PHONE(KOP_CODE),
)
GO

CREATE TABLE PUBLISHER(
	PUB_CODE CHAR(6) NOT NULL,
	PUB_NAME NVARCHAR(30) NOT NULL,
	PUB_PHONE CHAR(10) NOT NULL,
	PUB_ADDRESS NVARCHAR(100) NOT NULL

	CONSTRAINT PK_PUB_CODE PRIMARY KEY(PUB_CODE),
)
GO

ALTER TABLE PHONE
ADD CONSTRAINT FK_PUB_CODE FOREIGN KEY(PUB_CODE) REFERENCES PUBLISHER(PUB_CODE)

CREATE TABLE INVOICES_OUT(
	IVOUT_CODE CHAR(6) NOT NULL,
	P_NAME NVARCHAR(30) ,
	P_COST CHAR(100) ,
	CUS_CODE CHAR(6) ,
	IVOUT_AMOUNT CHAR(100) ,
	IVOUT_DATE DATETIME ,
	EMP_CODE CHAR(6) ,

	CONSTRAINT PK_IVOUT_CODE PRIMARY KEY(IVOUT_CODE),
	CONSTRAINT FK_P_NAME_IVOUT FOREIGN KEY(P_NAME) REFERENCES PHONE(P_NAME),
	CONSTRAINT FK_CUS_CODE_IVOUT FOREIGN KEY(CUS_CODE) REFERENCES CUSTOMER(CUS_CODE),
	CONSTRAINT FK_EMP_CODE_IVOUT FOREIGN KEY(EMP_CODE) REFERENCES EMPLOYEE(EMP_CODE),
)
GO

CREATE TABLE INVOICES_IN(
	IVIN_CODE CHAR(6) NOT NULL,
	P_NAME NVARCHAR(30) ,
	PUB_CODE CHAR(6) ,
	MA_NAME NVARCHAR(30) ,
	IVIN_DATE DATETIME,
	P_COSTIN CHAR(100) ,
	IVIN_AMOUNT CHAR(100) ,

	CONSTRAINT PK_IVIN_CODE PRIMARY KEY(IVIN_CODE),
	CONSTRAINT FK_P_NAME_IVIN FOREIGN KEY(P_NAME) REFERENCES PHONE(P_NAME),
	CONSTRAINT FK_PUB_CODE_IVIN FOREIGN KEY(PUB_CODE) REFERENCES PUBLISHER(PUB_CODE),
	CONSTRAINT FK_MA_NAME_IVIN FOREIGN KEY(MA_NAME) REFERENCES MANAGER(MA_NAME),
)
GO

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_MA_CODE_EMP FOREIGN KEY(MA_CODE) REFERENCES MANAGER(MA_CODE)''


INSERT INTO PHONE(P_CODE , P_NAME , P_BRAND , P_COST , P_COSTIN , P_NUMBER)
VALUES ('001' ,'IPhone 13' ,'IPHONE' , '15' , '10' ,'1'),
	   ('002' , 'IPhone 14', 'IPHONE' , '15' , '10' ,'1'),
	   ('003' ,'IPhone 7', 'IPHONE' , '15' , '10' ,'1'),
	   ('004' ,'IPhone 3', 'IPHONE' , '15' , '10' ,'1'),
	   ('005' ,'IPhone 4', 'IPHONE' , '15' , '10' ,'1');
		

INSERT INTO INVOICES_OUT(IVOUT_CODE ,P_NAME)
VALUES
	('001' , 'IPhone 13'),
	('002' , 'IPhone 14'),
	('003' , 'IPhone 7'),
	('004' , 'IPhone 13'),
	('005' , 'IPhone 13');