
--Lấy tất cả dữ liệu
SELECT * FROM dbo.PROFESSOR


--Lấy cột riêng
SELECT PROF_NUM ,PROF_FNAME , PROF_LNAME , PROF_EMAIL FROM PROFESSOR



--Tìm kiếm 
SELECT PROF_NUM ,PROF_FNAME , PROF_LNAME FROM PROFESSOR
WHERE PROF_NUM = '001' or PROF_NUM = '004' 


--Tăng dần theo thứ tự
SELECT PROF_NUM , PROF_FNAME , PROF_LNAME FROM PROFESSOR
WHERE PROF_NUM = '001' OR PROF_NUM = '005' OR PROF_NUM = '003'
ORDER BY PROF_NUM ASC




--Giảm dần theo thứ tự
SELECT PROF_NUM , PROF_FNAME , PROF_LNAME FROM PROFESSOR
WHERE PROF_NUM = '001' OR PROF_NUM = '005' OR PROF_NUM = '003'
ORDER BY PROF_NUM DESC



--INNER JOIN
SELECT DEPT_NAME FROM DEPARTMENT
INNER JOIN PROFESSOR
ON DEPARTMENT.DEPT_CODE = PROFESSOR.PROF_NUM



--LEFT JOIN
SELECT DEPT_NAME FROM DEPARTMENT
LEFT JOIN PROFESSOR
ON DEPARTMENT.DEPT_CODE = PROFESSOR.PROF_NUM


--RIGHT JOIN
SELECT DEPT_NAME FROM DEPARTMENT
RIGHT JOIN PROFESSOR
ON DEPARTMENT.DEPT_CODE = PROFESSOR.PROF_NUM



--FULL OUTER JOIN
SELECT DEPT_NAME FROM DEPARTMENT
FULL OUTER JOIN PROFESSOR
ON DEPARTMENT.DEPT_CODE = PROFESSOR.PROF_NUM

--Xóa 
DELETE FROM STUDENT
SELECT * FROM dbo.STUDENT
